[[https://melpa.org/#/exwm-firefox-evil][file:https://melpa.org/packages/exwm-firefox-evil-badge.svg]]
* exwm-firefox-evil - Evil-mode keys in firefox
exwm-firefox-evil makes firefox's control scheme modal. It uses vi-like keys and doesn't require any addons. It does this by implementing [[https://github.com/walseb/exwm-firefox-core][exwm-firefox-core]] which sends fake keys to firefox using exwm.

To get link-hints you have to download a link-hint addon to firefox and define a new function to send that key to firefox on call like those in =exwm-firefox-core=.

** Install
#+BEGIN_SRC emacs-lisp
  (require 'exwm-firefox-evil)
  ;; Auto enable exwm-firefox-evil-mode on all firefox buffers
  (add-hook 'exwm-manage-finish-hook 'exwm-firefox-evil-activate-if-firefox)
#+END_SRC

You also need to add ~escape~ to ~exwm-input-prefix-keys~ so that escape is passed to emacs instead of firefox.
#+BEGIN_SRC emacs-lisp
(dolist (k `(
	     escape
	     ))
  (cl-pushnew k exwm-input-prefix-keys))
#+END_SRC
Keep in mind that this affects all exwm-applications. If you want to get your escape key back in those applications you could bind the escape key to ~(exwm-input--fake-key 'escape)~ in your own minor mode that activates in all exwm-buffers just like I did in this package. For the conditional statement to avoid firefox buffers, just negate the checks in the function ~exwm-firefox-evil-activate-if-firefox~

** Know bugs
Mouse clicks only works in insert state
